[www]
; Tuning worker PHP-FPM untuk menangani beban konkurensi tinggi (IoT, Crawler, Web)
pm = dynamic
pm.max_children = 35
pm.start_servers = 6
pm.min_spare_servers = 4
pm.max_spare_servers = 12
pm.max_requests = 1000

; Perbesar buffer antrean socket koneksi FastCGI
listen.backlog = 2048

; Log & status
request_terminate_timeout = 300s
catch_workers_output = yes
